name: GameChat
version: 0.0.3
author: 2LS
main: dev._2lstudios.gamechat.GameChat
api-version: '1.13'
commands:
  chat:
    usage: /chat
  msg:
    usage: /msg
    aliases: [m, pm, tell]
  reply:
    usage: /reply
    aliases: [r]